# -*- coding: utf-8 -*-
"""
Created on Mon Aug 20 15:25:15 2018

@author: luismondragon
"""

adj_cal = 'chico rico puto alto viejo loco negro feo pequeño pendejo gordo falso'.split()
preps = 'asimismo través a ante bajo cabe con contra de desde en entre hacia hasta para por según sin so sobre tras durante mediante versus vía'.split()
prons = 'mi tu su nuestro nuestra vuestro vuestra mis tus sus nuestros nuestras vuestros vuestras mío mía tuyo tuya suyo suya míos mías tuyos tuyas suyos suyas adonde adónde algo alguien alguna algunas alguno algunos ambas ambos aquel aquél aquella aquélla aquellas aquéllas aquello aquellos aquéllos bastante bastantes como cómo conmigo consigo contigo cual cual cuál cuales cuáles cualesquiera cualquiera cualquier cuando cuándo cuanta cuánta cuantas cuántas cuanto cuánto cuantos cuántos cuya cuyas cuyo cuyos demás demasiada demasiadas demasiado demasiados donde dónde él ella ellas ello ellos esa ésa esas ésas ese ése eso esos ésos esta ésta estas éstas este éste esto estos éstos estotra estotro idem ídem la las le les lo lo los me media medias medio medios mí misma mismas mismo mismos mucha muchas mucho muchos nada nadie ninguna ningunas ninguno ningunos nos nosotras nosotros os otra otras otro otros poca pocas poco pocos qué que qué quien quién quienes quiénes quienesquiera quienquier quienquiera se sí tal tales tanta tantas tanto tantos te ti toda todas todo todos tú una unas uno unos usted ustedes varias varios vos vosotras vosotros yo'.split()
conjs = 'y e ni que pero mas aunque sino siquiera o u ora sea bien ya cerca lejos éste aquél pues porque puesto que ya que como más que igual menos así como si con tal que dado siempre aunque a pesar bien así luego tan tanto conque para porque cuando mientras antes apenas'.split()
arts = 'ningún algún alguno alguna algunos algunas esta ese estos eso sí esto este estas el la los las un uno una unos unas al del'.split() 
interjs =  'to replying ay eh hola adiós'.split()
advs = 'solo entonces sólo solamente arriba allí aquí allá ahí abajo adentro dentro afuera fuera música aplausos nunca no ahora cada cuando cuándo antes después todos tarde luego ayer temprano ya todavía anteayer aún pronto hoy aquí ahí allí cerca lejos fuera dentro alrededor aparte encima debajo delante detrás así bien mal despacio deprisa como mucho poco muy casi todo nada algo medio demasiado bastante más menos además incluso también'.split()
nouns = 'cabo día favor resto chapucero etcétera cosas personas gracias vez d[ia'.split()
adjs = 'nuevo último junto semana año importante siguiente siguientes próximo próxima grandes interesante gran grande claro clara bueno buena mala malo regular'.split()
nums = 'primer primero primera segundo segunda tercer tercero tercera cuarto cuarta quinto quinta sexto sexta séptimo séptima octavo octava noveno novena décimo décima sun una uno dos tres cuatro cinco seis siete ocho nueve diez once doce trece catorce quince diecicéis diecisiete dieciocho diecinueve veinte treinta cincuenta cien mil millones billones'.split()
meses = 'enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre'.split()
llevar = ['llevemos', 'llevase', 'llevarás', 'llevando', 'llevaríais', 'llevarías', 'llevasteis', 'llevaran', 'llevar', 'lleváramos', 'llevamos', 'lleváremos', 'llevaríamos', 'llevarais', 'llevares', 'llevado', 'llevare', 'llevases', 'llevábamos', 'llevaban', 'llevaré', 'llevéis', 'llevabais', 'lleváis', 'lleven', 'llevan', 'llevarían', 'llevaseis', 'llevaren', 'llevasen', 'lleves', 'llevaréis', 'llevaras', 'llevabas', 'llevad', 'llevaremos', 'llevará', 'llevásemos', 'llevas', 'lleva', 'lleve', 'llevara', 'llevaba', 'llevo', 'llevaría', 'llevaste', 'llevaron', 'llevarán', 'llevé', 'llevó', 'llevareis']
trabajar = ['trabajaste', 'trabajado', 'trabajaban', 'trabajaren', 'trabajaríamos', 'trabajando', 'trabajarías', 'trabaja', 'trabajemos', 'trabajé', 'trabajaras', 'trabajaseis', 'trabajaron', 'trabajarán', 'trabajad', 'trabajaremos', 'trabajéis', 'trabajaran', 'trabajáramos', 'trabajasteis', 'trabajaré', 'trabajaba', 'trabajara', 'trabajabais', 'trabajamos', 'trabajará', 'trabajábamos', 'trabajáis', 'trabajases', 'trabajas', 'trabajase', 'trabajareis', 'trabajarían', 'trabajare', 'trabajares', 'trabajan', 'trabajen', 'trabajaría', 'trabajáremos', 'trabajasen', 'trabajes', 'trabajaríais', 'trabajaréis', 'trabaje', 'trabajabas', 'trabajar', 'trabajo', 'trabajarais', 'trabajó', 'trabajarás', 'trabajásemos']
promover = ['promovían', 'promoverás', 'promueven', 'promuevas', 'promover', 'promoveréis', 'promovieran', 'promováis', 'promoviste', 'promoverá', 'promovería', 'promovieras', 'promovieren', 'promoverán', 'promovéis', 'promovieres', 'promueves', 'promovieseis', 'promueve', 'promovió', 'promovisteis', 'promoví', 'promuevan', 'promueva', 'promovimos', 'promovierais', 'promuevo', 'promoverías', 'promovía', 'promoviesen', 'promoveríamos', 'promoviéramos', 'promoverían', 'promoviere', 'promovamos', 'promoviésemos', 'promovemos', 'promovido', 'promoviéremos', 'promovíamos', 'promoveríais', 'promoviereis', 'promovieron', 'promoveré', 'promovíais', 'promovías', 'promovieses', 'promoviera', 'promoveremos', 'promoved', 'promoviendo', 'promoviese']
fortalecer = ['fortalezco', 'fortaleciereis', 'fortalecieses', 'fortalecierais', 'fortalezca', 'fortaleces', 'fortalecerán', 'fortaleciera', 'fortalecerás', 'fortaleciéremos', 'fortaleceremos', 'fortalecía', 'fortalecen', 'fortaleced', 'fortalezcamos', 'fortalecías', 'fortaleceréis', 'fortalecido', 'fortalecieron', 'fortalecéis', 'fortalecerías', 'fortalece', 'fortaleciste', 'fortalecieras', 'fortalecieseis', 'fortaleciese', 'fortaleciésemos', 'fortaleciendo', 'fortalezcan', 'fortalecíamos', 'fortalecer', 'fortalezcáis', 'fortaleciéramos', 'fortaleciere', 'fortalecieres', 'fortaleciesen', 'fortalecerá', 'fortalecían', 'fortalezcas', 'fortaleceríais', 'fortaleceré', 'fortalecerían', 'fortaleceríamos', 'fortalecieren', 'fortalecimos', 'fortalecemos', 'fortalecí', 'fortalecisteis', 'fortalecíais', 'fortalecieran', 'fortaleció', 'fortalecería']
destacar = ['destaco', 'destacas', 'destacarás', 'destacarán', 'destaquen', 'destacaríais', 'destacaste', 'destacaréis', 'destacabas', 'destacáremos', 'destaqué', 'destacara', 'destacabais', 'destacad', 'destacado', 'destacaseis', 'destacarían', 'destacase', 'destacasteis', 'destacaren', 'destacamos', 'destaca', 'destacaban', 'destacases', 'destacásemos', 'destacar', 'destacareis', 'destaques', 'destacando', 'destaque', 'destacaremos', 'destacábamos', 'destacaré', 'destacan', 'destacaran', 'destaquemos', 'destacáramos', 'destacaría', 'destacará', 'destacó', 'destacaron', 'destacaríamos', 'destacare', 'destacaras', 'destacáis', 'destacaba', 'destacarías', 'destacarais', 'destacares', 'destaquéis', 'destacasen']
impulsar = ['impulsando', 'impulsarían', 'impulsaran', 'impulsases', 'impulsaré', 'impulsaban', 'impulsaste', 'impulsen', 'impulsaren', 'impulsan', 'impulsaría', 'impulso', 'impulsa', 'impulsas', 'impulsad', 'impulsaríamos', 'impulsarán', 'impulséis', 'impulsaréis', 'impulsaras', 'impulsemos', 'impulsáis', 'impulsarais', 'impulsé', 'impulsará', 'impulsaba', 'impulsarías', 'impulsasen', 'impulsara', 'impulsaríais', 'impulsase', 'impulsáramos', 'impulsado', 'impulsábamos', 'impulsáremos', 'impulses', 'impulsaron', 'impulsareis', 'impulse', 'impulsarás', 'impulsares', 'impulsar', 'impulsásemos', 'impulsó', 'impulsaremos', 'impulsabais', 'impulsasteis', 'impulsabas', 'impulsamos', 'impulsaseis', 'impulsare']

haber = 'haber he has ha hay hemos han había habías habíamos habíais habían han habido habían hube hubiste hubo hubieron habré habría habrías habríamos habido haya hayas hayamos hayáis hayan hubiera hubiese hubiere hayan he'.split()
realizar = ['realizaba', 'realizaras', 'realizará', 'realizaseis', 'realizares', 'realizo', 'realizado', 'realizaron', 'realizaban', 'realizaréis', 'realizara', 'realizas', 'realizaremos', 'realizaren', 'realicemos', 'realizad', 'realizan', 'realices', 'realizaré', 'realizáramos', 'realizasen', 'realice', 'realizarás', 'realizar', 'realizábamos', 'realiza', 'realizando', 'realizaríais', 'realizarías', 'realizases', 'realizabas', 'realizásemos', 'realizase', 'realizareis', 'realizare', 'realizamos', 'realizabais', 'realizarían', 'realicé', 'realizarán', 'realizaría', 'realizaran', 'realizasteis', 'realizáis', 'realizó', 'realizaste', 'realizaríamos', 'realizáremos', 'realizarais', 'realicen', 'realicéis']
ser = 'somos seríais fueran seamos serás fuesen erais fuéremos seáis fuese fueren sea fueron fuésemos fueres seréis fuisteis sería era fue fuimos fuera soy serías fuereis fueses es fui fueseis sean serán seas fuere seremos fueras fuerais seríamos seré fuiste fuéramos sido serían eran sed siendo eras ser será sois eres éramos sé son'.split()
venir = ['vinieron', 'vinieran', 'vinieses', 'vengáis', 'vengan', 'vendríamos', 'vendréis', 'viene', 'vinimos', 'vinieres', 'venid', 'vine', 'viniendo', 'vendrás', 'vinieseis', 'ven', 'vengo', 'vengamos', 'venga', 'venido', 'viniere', 'viniste', 'vinierais', 'venía', 'venías', 'viniera', 'vienes', 'venir', 'venimos', 'viniese', 'viniereis', 'vendrías', 'vendré', 'vinisteis', 'viniesen', 'vendrán', 'vinieras', 'vinieren', 'vendríais', 'vengas', 'vendremos', 'vino', 'venían', 'vienen', 'vendrá', 'veníais', 'viniésemos', 'veníamos', 'venís', 'vendría', 'viniéramos', 'vendrían', 'viniéremos']
estar = 'estar estoy estás está estamos estáis están estás estaba estabas estaba estábamos estabais estaban estabas estuve estuviste estuvo estuvimos estuvisteis estuvieron estuviste estaré estarás estará estaremos estaréis estarán estarás estaría estarías estaría estaríamos estaríais estarían estarías presente esté estés esté estemos estéis estén estuviera estuvieras estuviéramos estuvierais estuvieran estuviese estuvieses estuviésemos estuvieses estuviere estuvieres estuviere estuviéremos estuviereis estuvieren estuvieres'.split()
tener = 'tener tendrá tendrán tendrás tendré tendréis tendremos tendría tendríais tendríamos tendrían tendrías tenéis tenemos tenga tengáis tengamos tengan tengas tengo tenía teníais teníamos tenían tenías tiene tienen tienes tuve tuviera tuvierais tuviéramos tuvieran tuvieras tuviere tuviereis tuviéremos tuvieren tuvieres tuvieron tuviese tuvieseis tuviésemos tuviesen tuvieses tuvimos tuviste tuvisteis tuvo tenido'.split()
hacer = 'hecho haz hagan haga haciendo hacer haced hizo hicisteis hiciste hicimos hicieses hiciesen hiciésemos hicieseis hiciese hiciese hicieron hicieres hicieren hiciéremos hiciereis hiciere hiciere hicieras hicieran hiciéramos hicierais hiciera hiciera hice hemos hecho he hecho has hecho harías harían haríamos haríais haría haría haremos haréis haré harás harán hará han hecho hago hagas hagan hagamos hagáis haga haga hacías hacían hacíamos hacíais hacía hacía haces hacen hacemos hacéis hace'.split()
ir = 'fue fuera fuera fuerais fuéramos fueran fueras fuere fuere fuereis fuéremos fueren fueres fueron fuese   fuese fueseis fuésemos fuesen fueses fui fuimos fuiste fuisteis iba iba ibais íbamos iban ibas irá irán irás iré iréis iremos iría iría iríais iríamos irían irías va vais vamos van vas vaya vaya vayáis vayamos vayan vayas voy ido ir yendo'.split()
poder = 'puedas podían podría pudimos pudieses podremos podríais pudiere pudieron pudiéremos pudieren podías poder podrás pude pudieras pudieseis pudiésemos pudo podréis pudiese pudiereis podríamos podrá pudieres podía pudierais pueden pudiendo podré podrán pudiste pudisteis poded podáis podamos puedan podrías podido pudieran podemos podrían puedo puedes podíamos pudiera pudiesen podéis pueda pudiéramos puede podíais'.split()
querer = 'quisiéramos queréis querrá queríamos quise querría quiera quisiese quisieres quieres querrán quería querré quisisteis quisieron quisieras quisieran queríais quisiera quiere quiso querréis queramos quisiéremos querremos quiero queráis quisieseis quisiere quered quisiésemos querríamos quisimos querías quisiesen querrían querrás queremos querríais queriendo querían quisiereis quieras querido quieran quisieses querer quisieren quieren quisierais quisiste'.split()
saber = 'supiésemos supierais sabes sabríais supimos sepa sepamos supiere sepáis supiéremos sabríamos saber supiéramos sabremos supiesen sabíais sabrás saben supieron supiera sabéis sepas sabrían sabed sabiendo sepan supe sabré sé sabréis sabían supiste supiereis supieran sabemos sabido sabría sabías sabrá supo sabrías supieseis supieras supieses supieres sabía sabe sabrán supieren supisteis supiese sabíamos'.split()
ver = 'verá vemos vi vieses ved veríais veías ven veréis verían vimos veíamos veíais vea veremos viste verán ves vieseis viéremos veríamos viera viéramos veis viere verás vieran visteis visto vieren vio veas ver vierais veía verías viésemos vieres ve veré vieras viese veáis veamos viesen vieron veían veo vean viendo viereis vería'.split()
poner = 'pusieren pondrías ponemos ponga pusiesen pondríamos pondría poniendo ponéis pondré pondrá pongamos ponían pusimos poned puso pusieras pondrán pondrían ponen pongan pondrás poníamos pusieses pongáis puesto pondremos poner pusiste pusiere ponías pusiéremos pondríais poníais pongas pusierais pongo pones pusiésemos pusiereis pusiera pusieron pusieseis pusiéramos pondréis pusieran pon pusieres pusiese ponía pusisteis pone puse'.split()
salir = 'salí salieren saliésemos salid salieran saldríais saliéramos salieseis salieras saliese saliste saldríamos saldréis saliereis saldremos salíamos salgáis salgamos salían salga saliendo salís salierais salir saldrá saldrán salíais salen salieres saldrían saldré saliéremos salimos salgas sale salido salieron salió sales sal salisteis saliesen saliere saliera salías salieses salgo saldrías salgan saldría salía saldrás'.split()
decir = 'decimos dijeron dijesen decid dijerais dijéramos dijéremos dijimos dijeras digáis dicen diciendo diré diréis diremos dirían diga dicho dirás dijeran decías decíamos dijera dijeses decía dirías digamos diría decís dices di dijeren dice digo dirán dijiste diríamos digan dijere dije dijeres dijisteis decíais dijo decir dirá dijese diríais dijereis decían dijésemos dijeseis digas'.split()
deber = 'deberéis debiste debíais debiesen debí debe debas debiese debieseis debieres debido debe deberán debería debierais debes deberían debimos debió debemos deberás deberías deban debiésemos debieran deberá debamos debieses debiéramos deber debiere deberé debiereis deba debieren debáis debieron debieras debiera debiéremos debiendo debo deberíais debed deben debían deberíamos debisteis deberemos debías debéis debía'.split()
creer = 'crean creéis creías creía creíste creo creyera creyéremos creíamos creemos creído creerás crees creyéramos creyereis creyerais creeríamos creísteis creyeseis creerías creer crea creyeras creyese creeréis creyesen creen creyeren creamos creeré creíais creyere creas creyendo cree creerá creyésemos creyeran creerían creed creían creyeron creeremos creyeses creerán creáis creí creyeres creyó creería creeríais creímos'.split()
dar = 'diésemos dé dad doy diese demos dieres daría diere dábamos darás diéremos dieses darías darían dabas dar daríamos daríais dimos das da daba daréis dieron diera damos dará dieran diéramos deis dais dieren den daban daremos des diesen dabais dan dio disteis dierais dieras dado daré diste dieseis dando di diereis darán'.split()

verbs = llevar + trabajar + promover + fortalecer + destacar + impulsar + realizar + venir + dar + creer + deber + haber + ser + estar + tener + hacer + ir + saber + poder + querer + ver + poner + salir + decir
stops = adj_cal + meses + adjs + nouns + nums + prons + preps + conjs + arts + interjs + advs + verbs
